### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by luigithekid** [geistinteractive/sails-filemaker#4]
My-MacBook-Pro:sails-filemaker myuser$ npm test

> sails-filemaker@0.2.1 test /Users/myuser/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker
> node test/integration/runner -R spec -b

module.js:338
    throw err;
          ^
Error: Cannot find module 'mocha'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/myuser/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/test/integration/runner.js:17:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Test failed.  See above for more details.

**Comment by toddgeist** [comment]
do you have sails or waterline installed?

**Comment by luigithekid** [comment]
I thought waterline was already bundled with Sails.
I also had mocha installed globally, so I went and installed it locally and got the following:
Marios-MacBook-Pro:sails-filemaker marioantonini$ npm test

> sails-filemaker@0.2.1 test /Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker
> node test/integration/runner -R spec -b

module.js:338
    throw err;
          ^
Error: Cannot find module 'captains-log'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/test/integration/runner.js:18:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Test failed.  See above for more details.
Marios-MacBook-Pro:sails-filemaker marioantonini$ 

Do I need to install locally al the required modules?

**Comment by toddgeist** [comment]
waterline is bundled with sails.  Captains log is also installed with Sails. Do you have sails up and running?

**Comment by luigithekid** [comment]
Ok, totally new at this. I did not have the project running.
Now I have a question, I lifted the project ($ sails lift) and tried the test again in a different terminal window... mind you I went and installed locally waterline, captains-log and waterline-adapter-tests and now I get a whole different "HUGE" wall of text, mind you I ran $ npm test with and without sails running, getting the same results:

Marios-MacBook-Pro:sails-filemaker marioantonini$ npm test

> sails-filemaker@0.2.1 test /Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker
> node test/integration/runner -R spec -b

info: Testing `sails-filemaker`, a Sails/Waterline adapter.
info: Running `waterline-adapter-tests` against 1 interfaces...
info: ( semantic )

debug: Latest draft of Waterline adapter interface spec:
debug: http://links.sailsjs.org/docs/plugins/adapters/interfaces



  Semantic Interface
    .create()
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at Request.callback (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:792:17)
    at IncomingMessage.<anonymous> (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:990:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Details:  Error: Bad Request

      1) should create a new record
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at Request.callback (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:792:17)
    at IncomingMessage.<anonymous> (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:990:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Details:  Error: Bad Request

      2) should return a generated PK
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at Request.callback (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:792:17)
    at IncomingMessage.<anonymous> (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:990:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Details:  Error: Bad Request

      3) should return generated timestamps
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at Request.callback (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:792:17)
    at IncomingMessage.<anonymous> (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:990:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Details:  Error: Bad Request

      4) should return a model instance
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      5) should normalize undefined values to null
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      6) should return rows in the correct order when creating multiple rows
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      overloaded usage of create
        7) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request


  Semantic Interface
    .createEach()
      8) should create a set of users
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      9) should insert 2 records verififed by find
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      10) should return model instances
{ [TypeError: Cannot read property 'id' of undefined] uncaught: true }

  Semantic Interface
    .destroy()
      a single record
        11) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request

      with numeric ID
        12) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request

      multiple records
        13) "before each" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request


  Semantic Interface
    .find()
      14) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request


  Semantic Interface
    .findOne()
      15) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request


  Semantic Interface
    .findOrCreate()
      16) should create a new record
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      17) should return a single record
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      18) should only have a single record in the database
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }
      19) should return a model instance
{ [TypeError: Cannot read property 'id' of undefined] uncaught: true }
      20) should take search criteria as values
{ [TypeError: Cannot read property 'id' of undefined] uncaught: true }
      21) should accept array of objects
{ [TypeError: Cannot read property '0' of undefined] uncaught: true }
      ✓ should return error if search criteria length does not match values

  Semantic Interface
    .findOrCreateEach()
      22) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request


  Semantic Interface
    Array Type
      with valid data
        23) should store proper array value
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    Binary Type
      with valid data
        24) should store proper binary value
{ [AssertionError: [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request
]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 
   Error (E_UNKNOWN) :: Encountered an unexpected error
   : Bad Request
       at Request.callback (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:792:17)
       at IncomingMessage.<anonymous> (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/sails-filemaker/node_modules/fms-js/node_modules/superagent/lib/node/index.js:990:12)
       at IncomingMessage.emit (events.js:129:20)
       at _stream_readable.js:908:16
       at process._tickCallback (node.js:355:11)
   
   Details:  Error: Bad Request
   ,
  generatedMessage: false,
  uncaught: true }

  Semantic Interface
    Boolean Type
      with valid data
        25) should store proper boolean value
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    Date Type
      with valid data
        26) should store proper date value
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    Float Type
      with valid data
        27) should store proper float value
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    Integer Type
      with valid data
        28) should store proper integer
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    JSON Type
      with valid data
        29) should store proper object value
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    String Type
      with valid data
        30) should store proper string value
{ [AssertionError: false == true]
  name: 'AssertionError',
  actual: false,
  expected: true,
  operator: '==',
  message: 'false == true',
  generatedMessage: true,
  uncaught: true }

  Semantic Interface
    .update()
      31) "before all" hook
Error (E_UNKNOWN) :: Encountered an unexpected error
Error (E_UNKNOWN) :: Encountered an unexpected error
: Bad Request
    at _stream_readable.js:908:16

Details:  Error: Bad Request



  1 passing (851ms)
  31 failing

  1) Semantic Interface .create() should create a new record:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  2) Semantic Interface .create() should return a generated PK:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  3) Semantic Interface .create() should return generated timestamps:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  4) Semantic Interface .create() should return a model instance:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  5) Semantic Interface .create() should normalize undefined values to null:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  6) Semantic Interface .create() should return rows in the correct order when creating multiple rows:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  7) Semantic Interface .create() overloaded usage of create "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  8) Semantic Interface .createEach() should create a set of users:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  9) Semantic Interface .createEach() should insert 2 records verififed by find:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at _stream_readable.js:908:16

  10) Semantic Interface .createEach() should return model instances:
     Uncaught TypeError: Cannot read property 'id' of undefined
  

  11) Semantic Interface .destroy() a single record "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  12) Semantic Interface .destroy() with numeric ID "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  13) Semantic Interface .destroy() multiple records "before each" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  14) Semantic Interface .find() "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  15) Semantic Interface .findOne() "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  16) Semantic Interface .findOrCreate() should create a new record:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  17) Semantic Interface .findOrCreate() should return a single record:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  18) Semantic Interface .findOrCreate() should only have a single record in the database:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at _stream_readable.js:908:16

  19) Semantic Interface .findOrCreate() should return a model instance:
     Uncaught TypeError: Cannot read property 'id' of undefined
  

  20) Semantic Interface .findOrCreate() should take search criteria as values:
     Uncaught TypeError: Cannot read property 'id' of undefined
  

  21) Semantic Interface .findOrCreate() should accept array of objects:
     Uncaught TypeError: Cannot read property '0' of undefined
  

  22) Semantic Interface .findOrCreateEach() "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  23) Semantic Interface Array Type with valid data should store proper array value:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  32) "after all" hook
{ [TypeError: undefined is not a function] uncaught: true }

  1 passing (861ms)
  32 failing

  1) Semantic Interface .create() should create a new record:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  2) Semantic Interface .create() should return a generated PK:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  3) Semantic Interface .create() should return generated timestamps:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  4) Semantic Interface .create() should return a model instance:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  5) Semantic Interface .create() should normalize undefined values to null:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  6) Semantic Interface .create() should return rows in the correct order when creating multiple rows:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  7) Semantic Interface .create() overloaded usage of create "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  8) Semantic Interface .createEach() should create a set of users:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  9) Semantic Interface .createEach() should insert 2 records verififed by find:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at _stream_readable.js:908:16

  10) Semantic Interface .createEach() should return model instances:
     Uncaught TypeError: Cannot read property 'id' of undefined
  

  11) Semantic Interface .destroy() a single record "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  12) Semantic Interface .destroy() with numeric ID "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  13) Semantic Interface .destroy() multiple records "before each" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  14) Semantic Interface .find() "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  15) Semantic Interface .findOne() "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  16) Semantic Interface .findOrCreate() should create a new record:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  17) Semantic Interface .findOrCreate() should return a single record:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

  18) Semantic Interface .findOrCreate() should only have a single record in the database:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at _stream_readable.js:908:16

  19) Semantic Interface .findOrCreate() should return a model instance:
     Uncaught TypeError: Cannot read property 'id' of undefined
  

  20) Semantic Interface .findOrCreate() should take search criteria as values:
     Uncaught TypeError: Cannot read property 'id' of undefined
  

  21) Semantic Interface .findOrCreate() should accept array of objects:
     Uncaught TypeError: Cannot read property '0' of undefined
  

  22) Semantic Interface .findOrCreateEach() "before all" hook:
     [Error (E_UNKNOWN) Encountered an unexpected error] Details:  Error: Bad Request

  Error (E_UNKNOWN) :: Encountered an unexpected error
  Error (E_UNKNOWN) :: Encountered an unexpected error
  : Bad Request
      at _stream_readable.js:908:16

  23) Semantic Interface Array Type with valid data should store proper array value:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
      
  

/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/mocha/lib/reporters/base.js:199
      var match = message.match(/^([^:]+): expected/);
                          ^
TypeError: undefined is not a function
    at /Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/mocha/lib/reporters/base.js:199:27
    at Array.forEach (native)
    at Function.exports.list (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/mocha/lib/reporters/base.js:161:12)
    at Spec.Base.epilogue (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/mocha/lib/reporters/base.js:319:10)
    at Runner.emit (events.js:129:20)
    at Runner.uncaught (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/mocha/lib/runner.js:593:8)
    at process.uncaught (/Users/marioantonini/Documents/SandboxWeb/node/testProject/node_modules/mocha/lib/runner.js:612:10)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
npm ERR! Test failed.  See above for more details.

**Comment by toddgeist** [comment]
It's ok, we are all new at this stuff.   you are now running all the tests.  Thats good.  But they are all failing.  Thats all that means.  You do not need to post the entire result.  It's sufficient to say that all tests are failing.

Now, do you have a FileMaker Server?
Do you have the test file thats included hosted on that server.
Did you change the configurations to match your FileMaker server?


Todd

**Comment by luigithekid** [comment]
Ok, this is where it might get tricky...
I have FMS on a network machine, not sure if that could cause issues.
However, I did change both myProject/config/connection.js and myProject/node_modules/sails-filemaker/test/integration/runner.js:
config: {
    schema: false,
    host: '10.10.10.219', // The ip address I see on my FM client when connecting to the server
    database: 'ContactsTest',
    userName: 'admin',
    password: ''
  }

**Comment by luigithekid** [comment]
and I am running $ npm test from sails-filemaker/

**Comment by toddgeist** [comment]
The test results are basically saying that you can't connect to your FileMaker server.  

Does your server have custom web publishing XML on?
Does your server have port 80 opened?

**Comment by luigithekid** [comment]
![screen shot 2015-06-22 at 2 42 43 pm](https://cloud.githubusercontent.com/assets/6372326/8293828/02012702-18ed-11e5-8ed5-d42b32b68e9f.png)
Regarding port 80, sorry but tbh I have no clue, I don't do any of the fms configuration. Is there an easy way to find out? I know that last part is totally out of the scope of this :(

**Comment by toddgeist** [comment]
What happens when you visit your FileMaker Server in a browser?  Do you see a web page that says FileMaker Server?

**Comment by luigithekid** [comment]
Blank page, once I figure what's wrong with the fm server I'll do more testing.

**Comment by toddgeist** [comment]
that'll do it  :-)
